apiVersion: v1
kind: Service
metadata:
   labels:
     app: backend-svc
   name: backend-svc
   namespace: principal
spec:
 type: NodePort
 ports:
  - protocol: TCP 
    port: 3000
    targetPort: 3000 
    nodePort: 30007

 selector:
    app: backend-dpl