apiVersion: v1
kind: Service
metadata:
   labels:
     app: postgres-svc
   name: postgres-svc
   namespace: principal
spec:
 type: ClusterIP
 ports:
  - protocol: TCP 
    port: 5432
    targetPort: 5432 

 selector:
    app: postgres-dpl