apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: principal
data:
   PORT: '3000'
   DB_NAME: postgres
   DB_HOST: postgres-svc.principal
   DB_PORT: '5432' 
   DB_USER: postgres
   DB_PASSWORD: '150158'